apiVersion: apps/v1
kind: Deployment
metadata:
  name: avito-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avito-app
  template:
    metadata:
      labels:
        app: avito-app
    spec:
      containers:
      - name: avito-app
        image: dock1155/avito-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: config-volume
          mountPath: /avito/config
      volumes:
      - name: config-volume
        configMap:
          name: app-config
