version: "3.8"
services:

  db:
    image: postgres:16.3
    container_name: db_app
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: avito_app_test
    command: ["sh", "/avito/docker/start.sh"]
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: